package com.gialen.tools.dao.repository.tools;

import com.gialen.tools.dao.entity.tools.DataTimerReportForm;
import com.gialen.tools.dao.entity.tools.DataTimerReportFormExample;
import java.util.List;

@org.springframework.stereotype.Repository
public interface DataTimerReportFormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    long countByExample(DataTimerReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    int insert(DataTimerReportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    int insertSelective(DataTimerReportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    List<DataTimerReportForm> selectByExample(DataTimerReportFormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    DataTimerReportForm selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DataTimerReportForm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_timer_report_form
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DataTimerReportForm record);

}