package com.gialen.tools.dao.repository.tools;

import com.gialen.tools.dao.entity.tools.ManagerAndDirector;
import com.gialen.tools.dao.entity.tools.ManagerAndDirectorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@org.springframework.stereotype.Repository
public interface ManagerAndDirectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    long countByExample(ManagerAndDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int deleteByExample(ManagerAndDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int insert(ManagerAndDirector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int insertSelective(ManagerAndDirector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    List<ManagerAndDirector> selectByExample(ManagerAndDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    ManagerAndDirector selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ManagerAndDirector record, @Param("example") ManagerAndDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ManagerAndDirector record, @Param("example") ManagerAndDirectorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ManagerAndDirector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manager_and_director
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ManagerAndDirector record);
}