package com.gialen.tools.dao.repository.tools;

import com.gialen.tools.dao.entity.tools.XiaojiaoData;
import com.gialen.tools.dao.entity.tools.XiaojiaoDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@org.springframework.stereotype.Repository
public interface XiaojiaoDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    long countByExample(XiaojiaoDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    int insert(XiaojiaoData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    int insertSelective(XiaojiaoData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    List<XiaojiaoData> selectByExample(XiaojiaoDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    XiaojiaoData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") XiaojiaoData record, @Param("example") XiaojiaoDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") XiaojiaoData record, @Param("example") XiaojiaoDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(XiaojiaoData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xiaojiao_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(XiaojiaoData record);
}