---
gialen:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/shopping_mall_test1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true

gialenmain:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/shopping_mall_test1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true

point:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://10.255.1.54:3306/gialen_gdata?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

settlement:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/gialen_settlement?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

tools:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/gialen_tools?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

customer:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/gialen_customer?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

#customer:
#  datasource:
#    password: gialenGIALEN123!@#
#    username: gialen_customer
#    url: jdbc:mysql://10.255.2.18:3306/gialen_customer?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true


order:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/gialen_order?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true


#order:
#  datasource:
#    password: reportREPORT1!
#    username: report
#    url: jdbc:mysql://10.255.2.21:3306/gialen_order?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
