---
gialen:
  datasource:
    password: gialen_shopping
    username: APP_REPORT
    url: jdbc:mysql://10.255.2.17:3306/shopping_mall_gialen_sc?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true

gialenmain:
  datasource:
    password: jiaomigo2018
    username: root
    url: jdbc:mysql://10.255.2.16:3306/shopping_mall_gialen_sc?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true

point:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://10.255.1.54:3306/gialen_gdata?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

settlement:
  datasource:
    password: reportREPORT1!
    username: report
    url: jdbc:mysql://10.255.2.21:3306/gialen_settlement?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

tools:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://10.255.1.54:3306/gialen_tools?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

customer:
  datasource:
    password: reportREPORT1!
    username: report
    url: jdbc:mysql://10.255.2.21:3306/gialen_customer?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
