---
gialen:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/shopping_mall_test1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

point:
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://10.255.1.54:3306/gialen_gdata?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

settlement:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/gialen_settlement?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true

tools:
  datasource:
    password: devtest
    username: dev
    url: jdbc:mysql://172.30.2.183:3306/gialen_tools?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true


