spring:
  redis:
    host: 172.30.2.176
    port: 6379
    database: 0
    timeout: 3000
    password: puwei#2018
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 8
        min-idle: 0