spring:
  redis:
    host: 10.255.1.64
    port: 6379
    timeout: 3000
    database: 0
#    password: jiaomigo2018
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 8
        min-idle: 0