package com.gialen.tools.dao.entity.gialen;

import java.util.ArrayList;
import java.util.List;

public class BlcCustomerRelationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    protected int offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    protected int limit;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public BlcCustomerRelationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public void setOffset(int offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public void setLimit(int limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCnCodeIsNull() {
            addCriterion("cn_code is null");
            return (Criteria) this;
        }

        public Criteria andCnCodeIsNotNull() {
            addCriterion("cn_code is not null");
            return (Criteria) this;
        }

        public Criteria andCnCodeEqualTo(String value) {
            addCriterion("cn_code =", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotEqualTo(String value) {
            addCriterion("cn_code <>", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeGreaterThan(String value) {
            addCriterion("cn_code >", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeGreaterThanOrEqualTo(String value) {
            addCriterion("cn_code >=", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeLessThan(String value) {
            addCriterion("cn_code <", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeLessThanOrEqualTo(String value) {
            addCriterion("cn_code <=", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeLike(String value) {
            addCriterion("cn_code like", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotLike(String value) {
            addCriterion("cn_code not like", value, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeIn(List<String> values) {
            addCriterion("cn_code in", values, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotIn(List<String> values) {
            addCriterion("cn_code not in", values, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeBetween(String value1, String value2) {
            addCriterion("cn_code between", value1, value2, "cnCode");
            return (Criteria) this;
        }

        public Criteria andCnCodeNotBetween(String value1, String value2) {
            addCriterion("cn_code not between", value1, value2, "cnCode");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNull() {
            addCriterion("log_date is null");
            return (Criteria) this;
        }

        public Criteria andLogDateIsNotNull() {
            addCriterion("log_date is not null");
            return (Criteria) this;
        }

        public Criteria andLogDateEqualTo(String value) {
            addCriterion("log_date =", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotEqualTo(String value) {
            addCriterion("log_date <>", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThan(String value) {
            addCriterion("log_date >", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateGreaterThanOrEqualTo(String value) {
            addCriterion("log_date >=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThan(String value) {
            addCriterion("log_date <", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLessThanOrEqualTo(String value) {
            addCriterion("log_date <=", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateLike(String value) {
            addCriterion("log_date like", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotLike(String value) {
            addCriterion("log_date not like", value, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateIn(List<String> values) {
            addCriterion("log_date in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotIn(List<String> values) {
            addCriterion("log_date not in", values, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateBetween(String value1, String value2) {
            addCriterion("log_date between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogDateNotBetween(String value1, String value2) {
            addCriterion("log_date not between", value1, value2, "logDate");
            return (Criteria) this;
        }

        public Criteria andLogMonthIsNull() {
            addCriterion("log_month is null");
            return (Criteria) this;
        }

        public Criteria andLogMonthIsNotNull() {
            addCriterion("log_month is not null");
            return (Criteria) this;
        }

        public Criteria andLogMonthEqualTo(Byte value) {
            addCriterion("log_month =", value, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthNotEqualTo(Byte value) {
            addCriterion("log_month <>", value, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthGreaterThan(Byte value) {
            addCriterion("log_month >", value, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthGreaterThanOrEqualTo(Byte value) {
            addCriterion("log_month >=", value, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthLessThan(Byte value) {
            addCriterion("log_month <", value, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthLessThanOrEqualTo(Byte value) {
            addCriterion("log_month <=", value, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthIn(List<Byte> values) {
            addCriterion("log_month in", values, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthNotIn(List<Byte> values) {
            addCriterion("log_month not in", values, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthBetween(Byte value1, Byte value2) {
            addCriterion("log_month between", value1, value2, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogMonthNotBetween(Byte value1, Byte value2) {
            addCriterion("log_month not between", value1, value2, "logMonth");
            return (Criteria) this;
        }

        public Criteria andLogYearIsNull() {
            addCriterion("log_year is null");
            return (Criteria) this;
        }

        public Criteria andLogYearIsNotNull() {
            addCriterion("log_year is not null");
            return (Criteria) this;
        }

        public Criteria andLogYearEqualTo(Short value) {
            addCriterion("log_year =", value, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearNotEqualTo(Short value) {
            addCriterion("log_year <>", value, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearGreaterThan(Short value) {
            addCriterion("log_year >", value, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearGreaterThanOrEqualTo(Short value) {
            addCriterion("log_year >=", value, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearLessThan(Short value) {
            addCriterion("log_year <", value, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearLessThanOrEqualTo(Short value) {
            addCriterion("log_year <=", value, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearIn(List<Short> values) {
            addCriterion("log_year in", values, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearNotIn(List<Short> values) {
            addCriterion("log_year not in", values, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearBetween(Short value1, Short value2) {
            addCriterion("log_year between", value1, value2, "logYear");
            return (Criteria) this;
        }

        public Criteria andLogYearNotBetween(Short value1, Short value2) {
            addCriterion("log_year not between", value1, value2, "logYear");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNull() {
            addCriterion("modify_date is null");
            return (Criteria) this;
        }

        public Criteria andModifyDateIsNotNull() {
            addCriterion("modify_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifyDateEqualTo(String value) {
            addCriterion("modify_date =", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotEqualTo(String value) {
            addCriterion("modify_date <>", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThan(String value) {
            addCriterion("modify_date >", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateGreaterThanOrEqualTo(String value) {
            addCriterion("modify_date >=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThan(String value) {
            addCriterion("modify_date <", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLessThanOrEqualTo(String value) {
            addCriterion("modify_date <=", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateLike(String value) {
            addCriterion("modify_date like", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotLike(String value) {
            addCriterion("modify_date not like", value, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateIn(List<String> values) {
            addCriterion("modify_date in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotIn(List<String> values) {
            addCriterion("modify_date not in", values, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateBetween(String value1, String value2) {
            addCriterion("modify_date between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andModifyDateNotBetween(String value1, String value2) {
            addCriterion("modify_date not between", value1, value2, "modifyDate");
            return (Criteria) this;
        }

        public Criteria andStateBussIsNull() {
            addCriterion("state_buss is null");
            return (Criteria) this;
        }

        public Criteria andStateBussIsNotNull() {
            addCriterion("state_buss is not null");
            return (Criteria) this;
        }

        public Criteria andStateBussEqualTo(Byte value) {
            addCriterion("state_buss =", value, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussNotEqualTo(Byte value) {
            addCriterion("state_buss <>", value, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussGreaterThan(Byte value) {
            addCriterion("state_buss >", value, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussGreaterThanOrEqualTo(Byte value) {
            addCriterion("state_buss >=", value, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussLessThan(Byte value) {
            addCriterion("state_buss <", value, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussLessThanOrEqualTo(Byte value) {
            addCriterion("state_buss <=", value, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussIn(List<Byte> values) {
            addCriterion("state_buss in", values, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussNotIn(List<Byte> values) {
            addCriterion("state_buss not in", values, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussBetween(Byte value1, Byte value2) {
            addCriterion("state_buss between", value1, value2, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateBussNotBetween(Byte value1, Byte value2) {
            addCriterion("state_buss not between", value1, value2, "stateBuss");
            return (Criteria) this;
        }

        public Criteria andStateDataIsNull() {
            addCriterion("state_data is null");
            return (Criteria) this;
        }

        public Criteria andStateDataIsNotNull() {
            addCriterion("state_data is not null");
            return (Criteria) this;
        }

        public Criteria andStateDataEqualTo(Byte value) {
            addCriterion("state_data =", value, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataNotEqualTo(Byte value) {
            addCriterion("state_data <>", value, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataGreaterThan(Byte value) {
            addCriterion("state_data >", value, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataGreaterThanOrEqualTo(Byte value) {
            addCriterion("state_data >=", value, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataLessThan(Byte value) {
            addCriterion("state_data <", value, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataLessThanOrEqualTo(Byte value) {
            addCriterion("state_data <=", value, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataIn(List<Byte> values) {
            addCriterion("state_data in", values, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataNotIn(List<Byte> values) {
            addCriterion("state_data not in", values, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataBetween(Byte value1, Byte value2) {
            addCriterion("state_data between", value1, value2, "stateData");
            return (Criteria) this;
        }

        public Criteria andStateDataNotBetween(Byte value1, Byte value2) {
            addCriterion("state_data not between", value1, value2, "stateData");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Long value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Long value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Long value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Long value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Long value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Long> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Long> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Long value1, Long value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Long value1, Long value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIsNull() {
            addCriterion("customer_type is null");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIsNotNull() {
            addCriterion("customer_type is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeEqualTo(Short value) {
            addCriterion("customer_type =", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotEqualTo(Short value) {
            addCriterion("customer_type <>", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeGreaterThan(Short value) {
            addCriterion("customer_type >", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("customer_type >=", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLessThan(Short value) {
            addCriterion("customer_type <", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeLessThanOrEqualTo(Short value) {
            addCriterion("customer_type <=", value, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeIn(List<Short> values) {
            addCriterion("customer_type in", values, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotIn(List<Short> values) {
            addCriterion("customer_type not in", values, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeBetween(Short value1, Short value2) {
            addCriterion("customer_type between", value1, value2, "customerType");
            return (Criteria) this;
        }

        public Criteria andCustomerTypeNotBetween(Short value1, Short value2) {
            addCriterion("customer_type not between", value1, value2, "customerType");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNull() {
            addCriterion("store_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreIdIsNotNull() {
            addCriterion("store_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreIdEqualTo(Long value) {
            addCriterion("store_id =", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotEqualTo(Long value) {
            addCriterion("store_id <>", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThan(Long value) {
            addCriterion("store_id >", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdGreaterThanOrEqualTo(Long value) {
            addCriterion("store_id >=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThan(Long value) {
            addCriterion("store_id <", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdLessThanOrEqualTo(Long value) {
            addCriterion("store_id <=", value, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdIn(List<Long> values) {
            addCriterion("store_id in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotIn(List<Long> values) {
            addCriterion("store_id not in", values, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdBetween(Long value1, Long value2) {
            addCriterion("store_id between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreIdNotBetween(Long value1, Long value2) {
            addCriterion("store_id not between", value1, value2, "storeId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdIsNull() {
            addCriterion("store_mgr_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdIsNotNull() {
            addCriterion("store_mgr_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdEqualTo(Long value) {
            addCriterion("store_mgr_id =", value, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdNotEqualTo(Long value) {
            addCriterion("store_mgr_id <>", value, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdGreaterThan(Long value) {
            addCriterion("store_mgr_id >", value, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("store_mgr_id >=", value, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdLessThan(Long value) {
            addCriterion("store_mgr_id <", value, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdLessThanOrEqualTo(Long value) {
            addCriterion("store_mgr_id <=", value, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdIn(List<Long> values) {
            addCriterion("store_mgr_id in", values, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdNotIn(List<Long> values) {
            addCriterion("store_mgr_id not in", values, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdBetween(Long value1, Long value2) {
            addCriterion("store_mgr_id between", value1, value2, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrIdNotBetween(Long value1, Long value2) {
            addCriterion("store_mgr_id not between", value1, value2, "storeMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdIsNull() {
            addCriterion("store_super_mgr_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdIsNotNull() {
            addCriterion("store_super_mgr_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdEqualTo(Long value) {
            addCriterion("store_super_mgr_id =", value, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdNotEqualTo(Long value) {
            addCriterion("store_super_mgr_id <>", value, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdGreaterThan(Long value) {
            addCriterion("store_super_mgr_id >", value, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdGreaterThanOrEqualTo(Long value) {
            addCriterion("store_super_mgr_id >=", value, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdLessThan(Long value) {
            addCriterion("store_super_mgr_id <", value, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdLessThanOrEqualTo(Long value) {
            addCriterion("store_super_mgr_id <=", value, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdIn(List<Long> values) {
            addCriterion("store_super_mgr_id in", values, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdNotIn(List<Long> values) {
            addCriterion("store_super_mgr_id not in", values, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdBetween(Long value1, Long value2) {
            addCriterion("store_super_mgr_id between", value1, value2, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrIdNotBetween(Long value1, Long value2) {
            addCriterion("store_super_mgr_id not between", value1, value2, "storeSuperMgrId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdIsNull() {
            addCriterion("customer_level_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdIsNotNull() {
            addCriterion("customer_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdEqualTo(Long value) {
            addCriterion("customer_level_id =", value, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdNotEqualTo(Long value) {
            addCriterion("customer_level_id <>", value, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdGreaterThan(Long value) {
            addCriterion("customer_level_id >", value, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("customer_level_id >=", value, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdLessThan(Long value) {
            addCriterion("customer_level_id <", value, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdLessThanOrEqualTo(Long value) {
            addCriterion("customer_level_id <=", value, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdIn(List<Long> values) {
            addCriterion("customer_level_id in", values, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdNotIn(List<Long> values) {
            addCriterion("customer_level_id not in", values, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdBetween(Long value1, Long value2) {
            addCriterion("customer_level_id between", value1, value2, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andCustomerLevelIdNotBetween(Long value1, Long value2) {
            addCriterion("customer_level_id not between", value1, value2, "customerLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdIsNull() {
            addCriterion("store_mgr_level_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdIsNotNull() {
            addCriterion("store_mgr_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdEqualTo(Long value) {
            addCriterion("store_mgr_level_id =", value, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdNotEqualTo(Long value) {
            addCriterion("store_mgr_level_id <>", value, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdGreaterThan(Long value) {
            addCriterion("store_mgr_level_id >", value, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("store_mgr_level_id >=", value, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdLessThan(Long value) {
            addCriterion("store_mgr_level_id <", value, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdLessThanOrEqualTo(Long value) {
            addCriterion("store_mgr_level_id <=", value, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdIn(List<Long> values) {
            addCriterion("store_mgr_level_id in", values, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdNotIn(List<Long> values) {
            addCriterion("store_mgr_level_id not in", values, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdBetween(Long value1, Long value2) {
            addCriterion("store_mgr_level_id between", value1, value2, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreMgrLevelIdNotBetween(Long value1, Long value2) {
            addCriterion("store_mgr_level_id not between", value1, value2, "storeMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdIsNull() {
            addCriterion("store_super_mgr_level_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdIsNotNull() {
            addCriterion("store_super_mgr_level_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdEqualTo(Long value) {
            addCriterion("store_super_mgr_level_id =", value, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdNotEqualTo(Long value) {
            addCriterion("store_super_mgr_level_id <>", value, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdGreaterThan(Long value) {
            addCriterion("store_super_mgr_level_id >", value, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("store_super_mgr_level_id >=", value, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdLessThan(Long value) {
            addCriterion("store_super_mgr_level_id <", value, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdLessThanOrEqualTo(Long value) {
            addCriterion("store_super_mgr_level_id <=", value, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdIn(List<Long> values) {
            addCriterion("store_super_mgr_level_id in", values, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdNotIn(List<Long> values) {
            addCriterion("store_super_mgr_level_id not in", values, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdBetween(Long value1, Long value2) {
            addCriterion("store_super_mgr_level_id between", value1, value2, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreSuperMgrLevelIdNotBetween(Long value1, Long value2) {
            addCriterion("store_super_mgr_level_id not between", value1, value2, "storeSuperMgrLevelId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdIsNull() {
            addCriterion("store_branch_id is null");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdIsNotNull() {
            addCriterion("store_branch_id is not null");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdEqualTo(Long value) {
            addCriterion("store_branch_id =", value, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdNotEqualTo(Long value) {
            addCriterion("store_branch_id <>", value, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdGreaterThan(Long value) {
            addCriterion("store_branch_id >", value, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdGreaterThanOrEqualTo(Long value) {
            addCriterion("store_branch_id >=", value, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdLessThan(Long value) {
            addCriterion("store_branch_id <", value, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdLessThanOrEqualTo(Long value) {
            addCriterion("store_branch_id <=", value, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdIn(List<Long> values) {
            addCriterion("store_branch_id in", values, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdNotIn(List<Long> values) {
            addCriterion("store_branch_id not in", values, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdBetween(Long value1, Long value2) {
            addCriterion("store_branch_id between", value1, value2, "storeBranchId");
            return (Criteria) this;
        }

        public Criteria andStoreBranchIdNotBetween(Long value1, Long value2) {
            addCriterion("store_branch_id not between", value1, value2, "storeBranchId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blc_customer_relation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table blc_customer_relation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}