package com.gialen.tools.dao.entity.gialen;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class BlcOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_ID
     *
     * @mbg.generated
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.CREATED_BY
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.DATE_CREATED
     *
     * @mbg.generated
     */
    private Date dateCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.DATE_UPDATED
     *
     * @mbg.generated
     */
    private Date dateUpdated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.UPDATED_BY
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.EMAIL_ADDRESS
     *
     * @mbg.generated
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.NAME
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_NUMBER
     *
     * @mbg.generated
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_STATUS
     *
     * @mbg.generated
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_SUBTOTAL
     *
     * @mbg.generated
     */
    private BigDecimal orderSubtotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.SUBMIT_DATE
     *
     * @mbg.generated
     */
    private Date submitDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_TOTAL
     *
     * @mbg.generated
     */
    private BigDecimal orderTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.TOTAL_SHIPPING
     *
     * @mbg.generated
     */
    private BigDecimal totalShipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.TOTAL_TAX
     *
     * @mbg.generated
     */
    private BigDecimal totalTax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.CURRENCY_CODE
     *
     * @mbg.generated
     */
    private String currencyCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.CUSTOMER_ID
     *
     * @mbg.generated
     */
    private Long customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.LOCALE_CODE
     *
     * @mbg.generated
     */
    private String localeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_SHIPPING_STATUS
     *
     * @mbg.generated
     */
    private String orderShippingStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_PAY_STATUS
     *
     * @mbg.generated
     */
    private String orderPayStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_REVIEW_STATUS
     *
     * @mbg.generated
     */
    private String orderReviewStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_PAY_MODE
     *
     * @mbg.generated
     */
    private String orderPayMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_PLATFORM_TYPE
     *
     * @mbg.generated
     */
    private String orderPlatformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_DELIVERY_NUMBER
     *
     * @mbg.generated
     */
    private String orderDeliveryNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_PAY_DATE
     *
     * @mbg.generated
     */
    private Date orderPayDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_SHIPPING_DATE
     *
     * @mbg.generated
     */
    private Date orderShippingDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_CHECK_STATS
     *
     * @mbg.generated
     */
    private String orderCheckStats;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_CHECK_DATE
     *
     * @mbg.generated
     */
    private Date orderCheckDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_TYPE
     *
     * @mbg.generated
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.order_mark
     *
     * @mbg.generated
     */
    private String orderMark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_PAY_WAY
     *
     * @mbg.generated
     */
    private String orderPayWay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.POST_TO_ERP_SUCCESS
     *
     * @mbg.generated
     */
    private Byte postToErpSuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.POST_TO_ERP_STAMP
     *
     * @mbg.generated
     */
    private Date postToErpStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.DELIVERY_COMPANY
     *
     * @mbg.generated
     */
    private String deliveryCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ONLINE_PAY_TOTAL
     *
     * @mbg.generated
     */
    private BigDecimal onlinePayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.BALANCE_PAY_TOTAL
     *
     * @mbg.generated
     */
    private BigDecimal balancePayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_COMPLETE_DATE
     *
     * @mbg.generated
     */
    private Date orderCompleteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.EXCHAGE_MONEY_POINT_PAY
     *
     * @mbg.generated
     */
    private BigDecimal exchageMoneyPointPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.POINT_PAY
     *
     * @mbg.generated
     */
    private Long pointPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.IS_PRE_SALE
     *
     * @mbg.generated
     */
    private Boolean isPreSale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ARRIVAL_FLAG
     *
     * @mbg.generated
     */
    private Boolean arrivalFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.DELIVERY_ORDER_ID
     *
     * @mbg.generated
     */
    private String deliveryOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.DELIVERY_D_ADDRESS_CODE
     *
     * @mbg.generated
     */
    private String deliveryDAddressCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.REBATE_BALANCE_PAY_TOTAL
     *
     * @mbg.generated
     */
    private BigDecimal rebateBalancePayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.OFFLINE_PAY_TOTAL
     *
     * @mbg.generated
     */
    private BigDecimal offlinePayTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.SCHEDULE_ORDER_ID
     *
     * @mbg.generated
     */
    private Long scheduleOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.total_weight
     *
     * @mbg.generated
     */
    private BigDecimal totalWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ANONYMOUS
     *
     * @mbg.generated
     */
    private Boolean anonymous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.CROWD_FUNDING_ITEM_ID
     *
     * @mbg.generated
     */
    private Long crowdFundingItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.DELETE_STATUS
     *
     * @mbg.generated
     */
    private Boolean deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.DELETE_DATE
     *
     * @mbg.generated
     */
    private Date deleteDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.RECOMMEND_CUSTOMER_ID
     *
     * @mbg.generated
     */
    private Long recommendCustomerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.coin_id
     *
     * @mbg.generated
     */
    private Long coinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.coupon_id
     *
     * @mbg.generated
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.pay_type
     *
     * @mbg.generated
     */
    private Byte payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.order_gift
     *
     * @mbg.generated
     */
    private Byte orderGift;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.ORDER_TOTAL_PAY
     *
     * @mbg.generated
     */
    private BigDecimal orderTotalPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.USER_DELETE
     *
     * @mbg.generated
     */
    private Integer userDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.is_can_apply_service
     *
     * @mbg.generated
     */
    private Integer isCanApplyService;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.INVOICE_STATUS
     *
     * @mbg.generated
     */
    private Boolean invoiceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.transaction_no
     *
     * @mbg.generated
     */
    private String transactionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.split_transaction_no
     *
     * @mbg.generated
     */
    private String splitTransactionNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.efast_send_status
     *
     * @mbg.generated
     */
    private String efastSendStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.order_pay_time
     *
     * @mbg.generated
     */
    private Long orderPayTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.complete_time
     *
     * @mbg.generated
     */
    private Long completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.confire_status
     *
     * @mbg.generated
     */
    private String confireStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.is_group_purchasing
     *
     * @mbg.generated
     */
    private Long isGroupPurchasing;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.wx_mini_program_last_update_time
     *
     * @mbg.generated
     */
    private Date wxMiniProgramLastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.split_order_flag
     *
     * @mbg.generated
     */
    private Integer splitOrderFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.is_earnest_acitvity
     *
     * @mbg.generated
     */
    private Byte isEarnestAcitvity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blc_order.customer_remark
     *
     * @mbg.generated
     */
    private String customerRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blc_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_ID
     *
     * @return the value of blc_order.ORDER_ID
     *
     * @mbg.generated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_ID
     *
     * @param orderId the value for blc_order.ORDER_ID
     *
     * @mbg.generated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.CREATED_BY
     *
     * @return the value of blc_order.CREATED_BY
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.CREATED_BY
     *
     * @param createdBy the value for blc_order.CREATED_BY
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.DATE_CREATED
     *
     * @return the value of blc_order.DATE_CREATED
     *
     * @mbg.generated
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.DATE_CREATED
     *
     * @param dateCreated the value for blc_order.DATE_CREATED
     *
     * @mbg.generated
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.DATE_UPDATED
     *
     * @return the value of blc_order.DATE_UPDATED
     *
     * @mbg.generated
     */
    public Date getDateUpdated() {
        return dateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.DATE_UPDATED
     *
     * @param dateUpdated the value for blc_order.DATE_UPDATED
     *
     * @mbg.generated
     */
    public void setDateUpdated(Date dateUpdated) {
        this.dateUpdated = dateUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.UPDATED_BY
     *
     * @return the value of blc_order.UPDATED_BY
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.UPDATED_BY
     *
     * @param updatedBy the value for blc_order.UPDATED_BY
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.EMAIL_ADDRESS
     *
     * @return the value of blc_order.EMAIL_ADDRESS
     *
     * @mbg.generated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.EMAIL_ADDRESS
     *
     * @param emailAddress the value for blc_order.EMAIL_ADDRESS
     *
     * @mbg.generated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress == null ? null : emailAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.NAME
     *
     * @return the value of blc_order.NAME
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.NAME
     *
     * @param name the value for blc_order.NAME
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_NUMBER
     *
     * @return the value of blc_order.ORDER_NUMBER
     *
     * @mbg.generated
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_NUMBER
     *
     * @param orderNumber the value for blc_order.ORDER_NUMBER
     *
     * @mbg.generated
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber == null ? null : orderNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_STATUS
     *
     * @return the value of blc_order.ORDER_STATUS
     *
     * @mbg.generated
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_STATUS
     *
     * @param orderStatus the value for blc_order.ORDER_STATUS
     *
     * @mbg.generated
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_SUBTOTAL
     *
     * @return the value of blc_order.ORDER_SUBTOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getOrderSubtotal() {
        return orderSubtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_SUBTOTAL
     *
     * @param orderSubtotal the value for blc_order.ORDER_SUBTOTAL
     *
     * @mbg.generated
     */
    public void setOrderSubtotal(BigDecimal orderSubtotal) {
        this.orderSubtotal = orderSubtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.SUBMIT_DATE
     *
     * @return the value of blc_order.SUBMIT_DATE
     *
     * @mbg.generated
     */
    public Date getSubmitDate() {
        return submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.SUBMIT_DATE
     *
     * @param submitDate the value for blc_order.SUBMIT_DATE
     *
     * @mbg.generated
     */
    public void setSubmitDate(Date submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_TOTAL
     *
     * @return the value of blc_order.ORDER_TOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getOrderTotal() {
        return orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_TOTAL
     *
     * @param orderTotal the value for blc_order.ORDER_TOTAL
     *
     * @mbg.generated
     */
    public void setOrderTotal(BigDecimal orderTotal) {
        this.orderTotal = orderTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.TOTAL_SHIPPING
     *
     * @return the value of blc_order.TOTAL_SHIPPING
     *
     * @mbg.generated
     */
    public BigDecimal getTotalShipping() {
        return totalShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.TOTAL_SHIPPING
     *
     * @param totalShipping the value for blc_order.TOTAL_SHIPPING
     *
     * @mbg.generated
     */
    public void setTotalShipping(BigDecimal totalShipping) {
        this.totalShipping = totalShipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.TOTAL_TAX
     *
     * @return the value of blc_order.TOTAL_TAX
     *
     * @mbg.generated
     */
    public BigDecimal getTotalTax() {
        return totalTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.TOTAL_TAX
     *
     * @param totalTax the value for blc_order.TOTAL_TAX
     *
     * @mbg.generated
     */
    public void setTotalTax(BigDecimal totalTax) {
        this.totalTax = totalTax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.CURRENCY_CODE
     *
     * @return the value of blc_order.CURRENCY_CODE
     *
     * @mbg.generated
     */
    public String getCurrencyCode() {
        return currencyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.CURRENCY_CODE
     *
     * @param currencyCode the value for blc_order.CURRENCY_CODE
     *
     * @mbg.generated
     */
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode == null ? null : currencyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.CUSTOMER_ID
     *
     * @return the value of blc_order.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.CUSTOMER_ID
     *
     * @param customerId the value for blc_order.CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.LOCALE_CODE
     *
     * @return the value of blc_order.LOCALE_CODE
     *
     * @mbg.generated
     */
    public String getLocaleCode() {
        return localeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.LOCALE_CODE
     *
     * @param localeCode the value for blc_order.LOCALE_CODE
     *
     * @mbg.generated
     */
    public void setLocaleCode(String localeCode) {
        this.localeCode = localeCode == null ? null : localeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_SHIPPING_STATUS
     *
     * @return the value of blc_order.ORDER_SHIPPING_STATUS
     *
     * @mbg.generated
     */
    public String getOrderShippingStatus() {
        return orderShippingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_SHIPPING_STATUS
     *
     * @param orderShippingStatus the value for blc_order.ORDER_SHIPPING_STATUS
     *
     * @mbg.generated
     */
    public void setOrderShippingStatus(String orderShippingStatus) {
        this.orderShippingStatus = orderShippingStatus == null ? null : orderShippingStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_PAY_STATUS
     *
     * @return the value of blc_order.ORDER_PAY_STATUS
     *
     * @mbg.generated
     */
    public String getOrderPayStatus() {
        return orderPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_PAY_STATUS
     *
     * @param orderPayStatus the value for blc_order.ORDER_PAY_STATUS
     *
     * @mbg.generated
     */
    public void setOrderPayStatus(String orderPayStatus) {
        this.orderPayStatus = orderPayStatus == null ? null : orderPayStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_REVIEW_STATUS
     *
     * @return the value of blc_order.ORDER_REVIEW_STATUS
     *
     * @mbg.generated
     */
    public String getOrderReviewStatus() {
        return orderReviewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_REVIEW_STATUS
     *
     * @param orderReviewStatus the value for blc_order.ORDER_REVIEW_STATUS
     *
     * @mbg.generated
     */
    public void setOrderReviewStatus(String orderReviewStatus) {
        this.orderReviewStatus = orderReviewStatus == null ? null : orderReviewStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_PAY_MODE
     *
     * @return the value of blc_order.ORDER_PAY_MODE
     *
     * @mbg.generated
     */
    public String getOrderPayMode() {
        return orderPayMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_PAY_MODE
     *
     * @param orderPayMode the value for blc_order.ORDER_PAY_MODE
     *
     * @mbg.generated
     */
    public void setOrderPayMode(String orderPayMode) {
        this.orderPayMode = orderPayMode == null ? null : orderPayMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_PLATFORM_TYPE
     *
     * @return the value of blc_order.ORDER_PLATFORM_TYPE
     *
     * @mbg.generated
     */
    public String getOrderPlatformType() {
        return orderPlatformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_PLATFORM_TYPE
     *
     * @param orderPlatformType the value for blc_order.ORDER_PLATFORM_TYPE
     *
     * @mbg.generated
     */
    public void setOrderPlatformType(String orderPlatformType) {
        this.orderPlatformType = orderPlatformType == null ? null : orderPlatformType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_DELIVERY_NUMBER
     *
     * @return the value of blc_order.ORDER_DELIVERY_NUMBER
     *
     * @mbg.generated
     */
    public String getOrderDeliveryNumber() {
        return orderDeliveryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_DELIVERY_NUMBER
     *
     * @param orderDeliveryNumber the value for blc_order.ORDER_DELIVERY_NUMBER
     *
     * @mbg.generated
     */
    public void setOrderDeliveryNumber(String orderDeliveryNumber) {
        this.orderDeliveryNumber = orderDeliveryNumber == null ? null : orderDeliveryNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_PAY_DATE
     *
     * @return the value of blc_order.ORDER_PAY_DATE
     *
     * @mbg.generated
     */
    public Date getOrderPayDate() {
        return orderPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_PAY_DATE
     *
     * @param orderPayDate the value for blc_order.ORDER_PAY_DATE
     *
     * @mbg.generated
     */
    public void setOrderPayDate(Date orderPayDate) {
        this.orderPayDate = orderPayDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_SHIPPING_DATE
     *
     * @return the value of blc_order.ORDER_SHIPPING_DATE
     *
     * @mbg.generated
     */
    public Date getOrderShippingDate() {
        return orderShippingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_SHIPPING_DATE
     *
     * @param orderShippingDate the value for blc_order.ORDER_SHIPPING_DATE
     *
     * @mbg.generated
     */
    public void setOrderShippingDate(Date orderShippingDate) {
        this.orderShippingDate = orderShippingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_CHECK_STATS
     *
     * @return the value of blc_order.ORDER_CHECK_STATS
     *
     * @mbg.generated
     */
    public String getOrderCheckStats() {
        return orderCheckStats;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_CHECK_STATS
     *
     * @param orderCheckStats the value for blc_order.ORDER_CHECK_STATS
     *
     * @mbg.generated
     */
    public void setOrderCheckStats(String orderCheckStats) {
        this.orderCheckStats = orderCheckStats == null ? null : orderCheckStats.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_CHECK_DATE
     *
     * @return the value of blc_order.ORDER_CHECK_DATE
     *
     * @mbg.generated
     */
    public Date getOrderCheckDate() {
        return orderCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_CHECK_DATE
     *
     * @param orderCheckDate the value for blc_order.ORDER_CHECK_DATE
     *
     * @mbg.generated
     */
    public void setOrderCheckDate(Date orderCheckDate) {
        this.orderCheckDate = orderCheckDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_TYPE
     *
     * @return the value of blc_order.ORDER_TYPE
     *
     * @mbg.generated
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_TYPE
     *
     * @param orderType the value for blc_order.ORDER_TYPE
     *
     * @mbg.generated
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.order_mark
     *
     * @return the value of blc_order.order_mark
     *
     * @mbg.generated
     */
    public String getOrderMark() {
        return orderMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.order_mark
     *
     * @param orderMark the value for blc_order.order_mark
     *
     * @mbg.generated
     */
    public void setOrderMark(String orderMark) {
        this.orderMark = orderMark == null ? null : orderMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.remark
     *
     * @return the value of blc_order.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.remark
     *
     * @param remark the value for blc_order.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_PAY_WAY
     *
     * @return the value of blc_order.ORDER_PAY_WAY
     *
     * @mbg.generated
     */
    public String getOrderPayWay() {
        return orderPayWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_PAY_WAY
     *
     * @param orderPayWay the value for blc_order.ORDER_PAY_WAY
     *
     * @mbg.generated
     */
    public void setOrderPayWay(String orderPayWay) {
        this.orderPayWay = orderPayWay == null ? null : orderPayWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.POST_TO_ERP_SUCCESS
     *
     * @return the value of blc_order.POST_TO_ERP_SUCCESS
     *
     * @mbg.generated
     */
    public Byte getPostToErpSuccess() {
        return postToErpSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.POST_TO_ERP_SUCCESS
     *
     * @param postToErpSuccess the value for blc_order.POST_TO_ERP_SUCCESS
     *
     * @mbg.generated
     */
    public void setPostToErpSuccess(Byte postToErpSuccess) {
        this.postToErpSuccess = postToErpSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.POST_TO_ERP_STAMP
     *
     * @return the value of blc_order.POST_TO_ERP_STAMP
     *
     * @mbg.generated
     */
    public Date getPostToErpStamp() {
        return postToErpStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.POST_TO_ERP_STAMP
     *
     * @param postToErpStamp the value for blc_order.POST_TO_ERP_STAMP
     *
     * @mbg.generated
     */
    public void setPostToErpStamp(Date postToErpStamp) {
        this.postToErpStamp = postToErpStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.DELIVERY_COMPANY
     *
     * @return the value of blc_order.DELIVERY_COMPANY
     *
     * @mbg.generated
     */
    public String getDeliveryCompany() {
        return deliveryCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.DELIVERY_COMPANY
     *
     * @param deliveryCompany the value for blc_order.DELIVERY_COMPANY
     *
     * @mbg.generated
     */
    public void setDeliveryCompany(String deliveryCompany) {
        this.deliveryCompany = deliveryCompany == null ? null : deliveryCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ONLINE_PAY_TOTAL
     *
     * @return the value of blc_order.ONLINE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getOnlinePayTotal() {
        return onlinePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ONLINE_PAY_TOTAL
     *
     * @param onlinePayTotal the value for blc_order.ONLINE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public void setOnlinePayTotal(BigDecimal onlinePayTotal) {
        this.onlinePayTotal = onlinePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.BALANCE_PAY_TOTAL
     *
     * @return the value of blc_order.BALANCE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getBalancePayTotal() {
        return balancePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.BALANCE_PAY_TOTAL
     *
     * @param balancePayTotal the value for blc_order.BALANCE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public void setBalancePayTotal(BigDecimal balancePayTotal) {
        this.balancePayTotal = balancePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_COMPLETE_DATE
     *
     * @return the value of blc_order.ORDER_COMPLETE_DATE
     *
     * @mbg.generated
     */
    public Date getOrderCompleteDate() {
        return orderCompleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_COMPLETE_DATE
     *
     * @param orderCompleteDate the value for blc_order.ORDER_COMPLETE_DATE
     *
     * @mbg.generated
     */
    public void setOrderCompleteDate(Date orderCompleteDate) {
        this.orderCompleteDate = orderCompleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.EXCHAGE_MONEY_POINT_PAY
     *
     * @return the value of blc_order.EXCHAGE_MONEY_POINT_PAY
     *
     * @mbg.generated
     */
    public BigDecimal getExchageMoneyPointPay() {
        return exchageMoneyPointPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.EXCHAGE_MONEY_POINT_PAY
     *
     * @param exchageMoneyPointPay the value for blc_order.EXCHAGE_MONEY_POINT_PAY
     *
     * @mbg.generated
     */
    public void setExchageMoneyPointPay(BigDecimal exchageMoneyPointPay) {
        this.exchageMoneyPointPay = exchageMoneyPointPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.POINT_PAY
     *
     * @return the value of blc_order.POINT_PAY
     *
     * @mbg.generated
     */
    public Long getPointPay() {
        return pointPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.POINT_PAY
     *
     * @param pointPay the value for blc_order.POINT_PAY
     *
     * @mbg.generated
     */
    public void setPointPay(Long pointPay) {
        this.pointPay = pointPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.IS_PRE_SALE
     *
     * @return the value of blc_order.IS_PRE_SALE
     *
     * @mbg.generated
     */
    public Boolean getIsPreSale() {
        return isPreSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.IS_PRE_SALE
     *
     * @param isPreSale the value for blc_order.IS_PRE_SALE
     *
     * @mbg.generated
     */
    public void setIsPreSale(Boolean isPreSale) {
        this.isPreSale = isPreSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ARRIVAL_FLAG
     *
     * @return the value of blc_order.ARRIVAL_FLAG
     *
     * @mbg.generated
     */
    public Boolean getArrivalFlag() {
        return arrivalFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ARRIVAL_FLAG
     *
     * @param arrivalFlag the value for blc_order.ARRIVAL_FLAG
     *
     * @mbg.generated
     */
    public void setArrivalFlag(Boolean arrivalFlag) {
        this.arrivalFlag = arrivalFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.DELIVERY_ORDER_ID
     *
     * @return the value of blc_order.DELIVERY_ORDER_ID
     *
     * @mbg.generated
     */
    public String getDeliveryOrderId() {
        return deliveryOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.DELIVERY_ORDER_ID
     *
     * @param deliveryOrderId the value for blc_order.DELIVERY_ORDER_ID
     *
     * @mbg.generated
     */
    public void setDeliveryOrderId(String deliveryOrderId) {
        this.deliveryOrderId = deliveryOrderId == null ? null : deliveryOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.DELIVERY_D_ADDRESS_CODE
     *
     * @return the value of blc_order.DELIVERY_D_ADDRESS_CODE
     *
     * @mbg.generated
     */
    public String getDeliveryDAddressCode() {
        return deliveryDAddressCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.DELIVERY_D_ADDRESS_CODE
     *
     * @param deliveryDAddressCode the value for blc_order.DELIVERY_D_ADDRESS_CODE
     *
     * @mbg.generated
     */
    public void setDeliveryDAddressCode(String deliveryDAddressCode) {
        this.deliveryDAddressCode = deliveryDAddressCode == null ? null : deliveryDAddressCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.REBATE_BALANCE_PAY_TOTAL
     *
     * @return the value of blc_order.REBATE_BALANCE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getRebateBalancePayTotal() {
        return rebateBalancePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.REBATE_BALANCE_PAY_TOTAL
     *
     * @param rebateBalancePayTotal the value for blc_order.REBATE_BALANCE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public void setRebateBalancePayTotal(BigDecimal rebateBalancePayTotal) {
        this.rebateBalancePayTotal = rebateBalancePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.OFFLINE_PAY_TOTAL
     *
     * @return the value of blc_order.OFFLINE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public BigDecimal getOfflinePayTotal() {
        return offlinePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.OFFLINE_PAY_TOTAL
     *
     * @param offlinePayTotal the value for blc_order.OFFLINE_PAY_TOTAL
     *
     * @mbg.generated
     */
    public void setOfflinePayTotal(BigDecimal offlinePayTotal) {
        this.offlinePayTotal = offlinePayTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.SCHEDULE_ORDER_ID
     *
     * @return the value of blc_order.SCHEDULE_ORDER_ID
     *
     * @mbg.generated
     */
    public Long getScheduleOrderId() {
        return scheduleOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.SCHEDULE_ORDER_ID
     *
     * @param scheduleOrderId the value for blc_order.SCHEDULE_ORDER_ID
     *
     * @mbg.generated
     */
    public void setScheduleOrderId(Long scheduleOrderId) {
        this.scheduleOrderId = scheduleOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.total_weight
     *
     * @return the value of blc_order.total_weight
     *
     * @mbg.generated
     */
    public BigDecimal getTotalWeight() {
        return totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.total_weight
     *
     * @param totalWeight the value for blc_order.total_weight
     *
     * @mbg.generated
     */
    public void setTotalWeight(BigDecimal totalWeight) {
        this.totalWeight = totalWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ANONYMOUS
     *
     * @return the value of blc_order.ANONYMOUS
     *
     * @mbg.generated
     */
    public Boolean getAnonymous() {
        return anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ANONYMOUS
     *
     * @param anonymous the value for blc_order.ANONYMOUS
     *
     * @mbg.generated
     */
    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.CROWD_FUNDING_ITEM_ID
     *
     * @return the value of blc_order.CROWD_FUNDING_ITEM_ID
     *
     * @mbg.generated
     */
    public Long getCrowdFundingItemId() {
        return crowdFundingItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.CROWD_FUNDING_ITEM_ID
     *
     * @param crowdFundingItemId the value for blc_order.CROWD_FUNDING_ITEM_ID
     *
     * @mbg.generated
     */
    public void setCrowdFundingItemId(Long crowdFundingItemId) {
        this.crowdFundingItemId = crowdFundingItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.DELETE_STATUS
     *
     * @return the value of blc_order.DELETE_STATUS
     *
     * @mbg.generated
     */
    public Boolean getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.DELETE_STATUS
     *
     * @param deleteStatus the value for blc_order.DELETE_STATUS
     *
     * @mbg.generated
     */
    public void setDeleteStatus(Boolean deleteStatus) {
        this.deleteStatus = deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.DELETE_DATE
     *
     * @return the value of blc_order.DELETE_DATE
     *
     * @mbg.generated
     */
    public Date getDeleteDate() {
        return deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.DELETE_DATE
     *
     * @param deleteDate the value for blc_order.DELETE_DATE
     *
     * @mbg.generated
     */
    public void setDeleteDate(Date deleteDate) {
        this.deleteDate = deleteDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.RECOMMEND_CUSTOMER_ID
     *
     * @return the value of blc_order.RECOMMEND_CUSTOMER_ID
     *
     * @mbg.generated
     */
    public Long getRecommendCustomerId() {
        return recommendCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.RECOMMEND_CUSTOMER_ID
     *
     * @param recommendCustomerId the value for blc_order.RECOMMEND_CUSTOMER_ID
     *
     * @mbg.generated
     */
    public void setRecommendCustomerId(Long recommendCustomerId) {
        this.recommendCustomerId = recommendCustomerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.coin_id
     *
     * @return the value of blc_order.coin_id
     *
     * @mbg.generated
     */
    public Long getCoinId() {
        return coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.coin_id
     *
     * @param coinId the value for blc_order.coin_id
     *
     * @mbg.generated
     */
    public void setCoinId(Long coinId) {
        this.coinId = coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.coupon_id
     *
     * @return the value of blc_order.coupon_id
     *
     * @mbg.generated
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.coupon_id
     *
     * @param couponId the value for blc_order.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.pay_type
     *
     * @return the value of blc_order.pay_type
     *
     * @mbg.generated
     */
    public Byte getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.pay_type
     *
     * @param payType the value for blc_order.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Byte payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.order_gift
     *
     * @return the value of blc_order.order_gift
     *
     * @mbg.generated
     */
    public Byte getOrderGift() {
        return orderGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.order_gift
     *
     * @param orderGift the value for blc_order.order_gift
     *
     * @mbg.generated
     */
    public void setOrderGift(Byte orderGift) {
        this.orderGift = orderGift;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.ORDER_TOTAL_PAY
     *
     * @return the value of blc_order.ORDER_TOTAL_PAY
     *
     * @mbg.generated
     */
    public BigDecimal getOrderTotalPay() {
        return orderTotalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.ORDER_TOTAL_PAY
     *
     * @param orderTotalPay the value for blc_order.ORDER_TOTAL_PAY
     *
     * @mbg.generated
     */
    public void setOrderTotalPay(BigDecimal orderTotalPay) {
        this.orderTotalPay = orderTotalPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.USER_DELETE
     *
     * @return the value of blc_order.USER_DELETE
     *
     * @mbg.generated
     */
    public Integer getUserDelete() {
        return userDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.USER_DELETE
     *
     * @param userDelete the value for blc_order.USER_DELETE
     *
     * @mbg.generated
     */
    public void setUserDelete(Integer userDelete) {
        this.userDelete = userDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.is_can_apply_service
     *
     * @return the value of blc_order.is_can_apply_service
     *
     * @mbg.generated
     */
    public Integer getIsCanApplyService() {
        return isCanApplyService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.is_can_apply_service
     *
     * @param isCanApplyService the value for blc_order.is_can_apply_service
     *
     * @mbg.generated
     */
    public void setIsCanApplyService(Integer isCanApplyService) {
        this.isCanApplyService = isCanApplyService;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.INVOICE_STATUS
     *
     * @return the value of blc_order.INVOICE_STATUS
     *
     * @mbg.generated
     */
    public Boolean getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.INVOICE_STATUS
     *
     * @param invoiceStatus the value for blc_order.INVOICE_STATUS
     *
     * @mbg.generated
     */
    public void setInvoiceStatus(Boolean invoiceStatus) {
        this.invoiceStatus = invoiceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.transaction_no
     *
     * @return the value of blc_order.transaction_no
     *
     * @mbg.generated
     */
    public String getTransactionNo() {
        return transactionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.transaction_no
     *
     * @param transactionNo the value for blc_order.transaction_no
     *
     * @mbg.generated
     */
    public void setTransactionNo(String transactionNo) {
        this.transactionNo = transactionNo == null ? null : transactionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.split_transaction_no
     *
     * @return the value of blc_order.split_transaction_no
     *
     * @mbg.generated
     */
    public String getSplitTransactionNo() {
        return splitTransactionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.split_transaction_no
     *
     * @param splitTransactionNo the value for blc_order.split_transaction_no
     *
     * @mbg.generated
     */
    public void setSplitTransactionNo(String splitTransactionNo) {
        this.splitTransactionNo = splitTransactionNo == null ? null : splitTransactionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.efast_send_status
     *
     * @return the value of blc_order.efast_send_status
     *
     * @mbg.generated
     */
    public String getEfastSendStatus() {
        return efastSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.efast_send_status
     *
     * @param efastSendStatus the value for blc_order.efast_send_status
     *
     * @mbg.generated
     */
    public void setEfastSendStatus(String efastSendStatus) {
        this.efastSendStatus = efastSendStatus == null ? null : efastSendStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.order_pay_time
     *
     * @return the value of blc_order.order_pay_time
     *
     * @mbg.generated
     */
    public Long getOrderPayTime() {
        return orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.order_pay_time
     *
     * @param orderPayTime the value for blc_order.order_pay_time
     *
     * @mbg.generated
     */
    public void setOrderPayTime(Long orderPayTime) {
        this.orderPayTime = orderPayTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.complete_time
     *
     * @return the value of blc_order.complete_time
     *
     * @mbg.generated
     */
    public Long getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.complete_time
     *
     * @param completeTime the value for blc_order.complete_time
     *
     * @mbg.generated
     */
    public void setCompleteTime(Long completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.confire_status
     *
     * @return the value of blc_order.confire_status
     *
     * @mbg.generated
     */
    public String getConfireStatus() {
        return confireStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.confire_status
     *
     * @param confireStatus the value for blc_order.confire_status
     *
     * @mbg.generated
     */
    public void setConfireStatus(String confireStatus) {
        this.confireStatus = confireStatus == null ? null : confireStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.is_group_purchasing
     *
     * @return the value of blc_order.is_group_purchasing
     *
     * @mbg.generated
     */
    public Long getIsGroupPurchasing() {
        return isGroupPurchasing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.is_group_purchasing
     *
     * @param isGroupPurchasing the value for blc_order.is_group_purchasing
     *
     * @mbg.generated
     */
    public void setIsGroupPurchasing(Long isGroupPurchasing) {
        this.isGroupPurchasing = isGroupPurchasing;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.wx_mini_program_last_update_time
     *
     * @return the value of blc_order.wx_mini_program_last_update_time
     *
     * @mbg.generated
     */
    public Date getWxMiniProgramLastUpdateTime() {
        return wxMiniProgramLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.wx_mini_program_last_update_time
     *
     * @param wxMiniProgramLastUpdateTime the value for blc_order.wx_mini_program_last_update_time
     *
     * @mbg.generated
     */
    public void setWxMiniProgramLastUpdateTime(Date wxMiniProgramLastUpdateTime) {
        this.wxMiniProgramLastUpdateTime = wxMiniProgramLastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.split_order_flag
     *
     * @return the value of blc_order.split_order_flag
     *
     * @mbg.generated
     */
    public Integer getSplitOrderFlag() {
        return splitOrderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.split_order_flag
     *
     * @param splitOrderFlag the value for blc_order.split_order_flag
     *
     * @mbg.generated
     */
    public void setSplitOrderFlag(Integer splitOrderFlag) {
        this.splitOrderFlag = splitOrderFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.is_earnest_acitvity
     *
     * @return the value of blc_order.is_earnest_acitvity
     *
     * @mbg.generated
     */
    public Byte getIsEarnestAcitvity() {
        return isEarnestAcitvity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.is_earnest_acitvity
     *
     * @param isEarnestAcitvity the value for blc_order.is_earnest_acitvity
     *
     * @mbg.generated
     */
    public void setIsEarnestAcitvity(Byte isEarnestAcitvity) {
        this.isEarnestAcitvity = isEarnestAcitvity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blc_order.customer_remark
     *
     * @return the value of blc_order.customer_remark
     *
     * @mbg.generated
     */
    public String getCustomerRemark() {
        return customerRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blc_order.customer_remark
     *
     * @param customerRemark the value for blc_order.customer_remark
     *
     * @mbg.generated
     */
    public void setCustomerRemark(String customerRemark) {
        this.customerRemark = customerRemark == null ? null : customerRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_order
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        BlcOrder other = (BlcOrder) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getDateCreated() == null ? other.getDateCreated() == null : this.getDateCreated().equals(other.getDateCreated()))
            && (this.getDateUpdated() == null ? other.getDateUpdated() == null : this.getDateUpdated().equals(other.getDateUpdated()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()))
            && (this.getEmailAddress() == null ? other.getEmailAddress() == null : this.getEmailAddress().equals(other.getEmailAddress()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getOrderNumber() == null ? other.getOrderNumber() == null : this.getOrderNumber().equals(other.getOrderNumber()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getOrderSubtotal() == null ? other.getOrderSubtotal() == null : this.getOrderSubtotal().equals(other.getOrderSubtotal()))
            && (this.getSubmitDate() == null ? other.getSubmitDate() == null : this.getSubmitDate().equals(other.getSubmitDate()))
            && (this.getOrderTotal() == null ? other.getOrderTotal() == null : this.getOrderTotal().equals(other.getOrderTotal()))
            && (this.getTotalShipping() == null ? other.getTotalShipping() == null : this.getTotalShipping().equals(other.getTotalShipping()))
            && (this.getTotalTax() == null ? other.getTotalTax() == null : this.getTotalTax().equals(other.getTotalTax()))
            && (this.getCurrencyCode() == null ? other.getCurrencyCode() == null : this.getCurrencyCode().equals(other.getCurrencyCode()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getLocaleCode() == null ? other.getLocaleCode() == null : this.getLocaleCode().equals(other.getLocaleCode()))
            && (this.getOrderShippingStatus() == null ? other.getOrderShippingStatus() == null : this.getOrderShippingStatus().equals(other.getOrderShippingStatus()))
            && (this.getOrderPayStatus() == null ? other.getOrderPayStatus() == null : this.getOrderPayStatus().equals(other.getOrderPayStatus()))
            && (this.getOrderReviewStatus() == null ? other.getOrderReviewStatus() == null : this.getOrderReviewStatus().equals(other.getOrderReviewStatus()))
            && (this.getOrderPayMode() == null ? other.getOrderPayMode() == null : this.getOrderPayMode().equals(other.getOrderPayMode()))
            && (this.getOrderPlatformType() == null ? other.getOrderPlatformType() == null : this.getOrderPlatformType().equals(other.getOrderPlatformType()))
            && (this.getOrderDeliveryNumber() == null ? other.getOrderDeliveryNumber() == null : this.getOrderDeliveryNumber().equals(other.getOrderDeliveryNumber()))
            && (this.getOrderPayDate() == null ? other.getOrderPayDate() == null : this.getOrderPayDate().equals(other.getOrderPayDate()))
            && (this.getOrderShippingDate() == null ? other.getOrderShippingDate() == null : this.getOrderShippingDate().equals(other.getOrderShippingDate()))
            && (this.getOrderCheckStats() == null ? other.getOrderCheckStats() == null : this.getOrderCheckStats().equals(other.getOrderCheckStats()))
            && (this.getOrderCheckDate() == null ? other.getOrderCheckDate() == null : this.getOrderCheckDate().equals(other.getOrderCheckDate()))
            && (this.getOrderType() == null ? other.getOrderType() == null : this.getOrderType().equals(other.getOrderType()))
            && (this.getOrderMark() == null ? other.getOrderMark() == null : this.getOrderMark().equals(other.getOrderMark()))
            && (this.getRemark() == null ? other.getRemark() == null : this.getRemark().equals(other.getRemark()))
            && (this.getOrderPayWay() == null ? other.getOrderPayWay() == null : this.getOrderPayWay().equals(other.getOrderPayWay()))
            && (this.getPostToErpSuccess() == null ? other.getPostToErpSuccess() == null : this.getPostToErpSuccess().equals(other.getPostToErpSuccess()))
            && (this.getPostToErpStamp() == null ? other.getPostToErpStamp() == null : this.getPostToErpStamp().equals(other.getPostToErpStamp()))
            && (this.getDeliveryCompany() == null ? other.getDeliveryCompany() == null : this.getDeliveryCompany().equals(other.getDeliveryCompany()))
            && (this.getOnlinePayTotal() == null ? other.getOnlinePayTotal() == null : this.getOnlinePayTotal().equals(other.getOnlinePayTotal()))
            && (this.getBalancePayTotal() == null ? other.getBalancePayTotal() == null : this.getBalancePayTotal().equals(other.getBalancePayTotal()))
            && (this.getOrderCompleteDate() == null ? other.getOrderCompleteDate() == null : this.getOrderCompleteDate().equals(other.getOrderCompleteDate()))
            && (this.getExchageMoneyPointPay() == null ? other.getExchageMoneyPointPay() == null : this.getExchageMoneyPointPay().equals(other.getExchageMoneyPointPay()))
            && (this.getPointPay() == null ? other.getPointPay() == null : this.getPointPay().equals(other.getPointPay()))
            && (this.getIsPreSale() == null ? other.getIsPreSale() == null : this.getIsPreSale().equals(other.getIsPreSale()))
            && (this.getArrivalFlag() == null ? other.getArrivalFlag() == null : this.getArrivalFlag().equals(other.getArrivalFlag()))
            && (this.getDeliveryOrderId() == null ? other.getDeliveryOrderId() == null : this.getDeliveryOrderId().equals(other.getDeliveryOrderId()))
            && (this.getDeliveryDAddressCode() == null ? other.getDeliveryDAddressCode() == null : this.getDeliveryDAddressCode().equals(other.getDeliveryDAddressCode()))
            && (this.getRebateBalancePayTotal() == null ? other.getRebateBalancePayTotal() == null : this.getRebateBalancePayTotal().equals(other.getRebateBalancePayTotal()))
            && (this.getOfflinePayTotal() == null ? other.getOfflinePayTotal() == null : this.getOfflinePayTotal().equals(other.getOfflinePayTotal()))
            && (this.getScheduleOrderId() == null ? other.getScheduleOrderId() == null : this.getScheduleOrderId().equals(other.getScheduleOrderId()))
            && (this.getTotalWeight() == null ? other.getTotalWeight() == null : this.getTotalWeight().equals(other.getTotalWeight()))
            && (this.getAnonymous() == null ? other.getAnonymous() == null : this.getAnonymous().equals(other.getAnonymous()))
            && (this.getCrowdFundingItemId() == null ? other.getCrowdFundingItemId() == null : this.getCrowdFundingItemId().equals(other.getCrowdFundingItemId()))
            && (this.getDeleteStatus() == null ? other.getDeleteStatus() == null : this.getDeleteStatus().equals(other.getDeleteStatus()))
            && (this.getDeleteDate() == null ? other.getDeleteDate() == null : this.getDeleteDate().equals(other.getDeleteDate()))
            && (this.getRecommendCustomerId() == null ? other.getRecommendCustomerId() == null : this.getRecommendCustomerId().equals(other.getRecommendCustomerId()))
            && (this.getCoinId() == null ? other.getCoinId() == null : this.getCoinId().equals(other.getCoinId()))
            && (this.getCouponId() == null ? other.getCouponId() == null : this.getCouponId().equals(other.getCouponId()))
            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
            && (this.getOrderGift() == null ? other.getOrderGift() == null : this.getOrderGift().equals(other.getOrderGift()))
            && (this.getOrderTotalPay() == null ? other.getOrderTotalPay() == null : this.getOrderTotalPay().equals(other.getOrderTotalPay()))
            && (this.getUserDelete() == null ? other.getUserDelete() == null : this.getUserDelete().equals(other.getUserDelete()))
            && (this.getIsCanApplyService() == null ? other.getIsCanApplyService() == null : this.getIsCanApplyService().equals(other.getIsCanApplyService()))
            && (this.getInvoiceStatus() == null ? other.getInvoiceStatus() == null : this.getInvoiceStatus().equals(other.getInvoiceStatus()))
            && (this.getTransactionNo() == null ? other.getTransactionNo() == null : this.getTransactionNo().equals(other.getTransactionNo()))
            && (this.getSplitTransactionNo() == null ? other.getSplitTransactionNo() == null : this.getSplitTransactionNo().equals(other.getSplitTransactionNo()))
            && (this.getEfastSendStatus() == null ? other.getEfastSendStatus() == null : this.getEfastSendStatus().equals(other.getEfastSendStatus()))
            && (this.getOrderPayTime() == null ? other.getOrderPayTime() == null : this.getOrderPayTime().equals(other.getOrderPayTime()))
            && (this.getCompleteTime() == null ? other.getCompleteTime() == null : this.getCompleteTime().equals(other.getCompleteTime()))
            && (this.getConfireStatus() == null ? other.getConfireStatus() == null : this.getConfireStatus().equals(other.getConfireStatus()))
            && (this.getIsGroupPurchasing() == null ? other.getIsGroupPurchasing() == null : this.getIsGroupPurchasing().equals(other.getIsGroupPurchasing()))
            && (this.getWxMiniProgramLastUpdateTime() == null ? other.getWxMiniProgramLastUpdateTime() == null : this.getWxMiniProgramLastUpdateTime().equals(other.getWxMiniProgramLastUpdateTime()))
            && (this.getSplitOrderFlag() == null ? other.getSplitOrderFlag() == null : this.getSplitOrderFlag().equals(other.getSplitOrderFlag()))
            && (this.getIsEarnestAcitvity() == null ? other.getIsEarnestAcitvity() == null : this.getIsEarnestAcitvity().equals(other.getIsEarnestAcitvity()))
            && (this.getCustomerRemark() == null ? other.getCustomerRemark() == null : this.getCustomerRemark().equals(other.getCustomerRemark()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_order
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getDateCreated() == null) ? 0 : getDateCreated().hashCode());
        result = prime * result + ((getDateUpdated() == null) ? 0 : getDateUpdated().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        result = prime * result + ((getEmailAddress() == null) ? 0 : getEmailAddress().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getOrderNumber() == null) ? 0 : getOrderNumber().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getOrderSubtotal() == null) ? 0 : getOrderSubtotal().hashCode());
        result = prime * result + ((getSubmitDate() == null) ? 0 : getSubmitDate().hashCode());
        result = prime * result + ((getOrderTotal() == null) ? 0 : getOrderTotal().hashCode());
        result = prime * result + ((getTotalShipping() == null) ? 0 : getTotalShipping().hashCode());
        result = prime * result + ((getTotalTax() == null) ? 0 : getTotalTax().hashCode());
        result = prime * result + ((getCurrencyCode() == null) ? 0 : getCurrencyCode().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getLocaleCode() == null) ? 0 : getLocaleCode().hashCode());
        result = prime * result + ((getOrderShippingStatus() == null) ? 0 : getOrderShippingStatus().hashCode());
        result = prime * result + ((getOrderPayStatus() == null) ? 0 : getOrderPayStatus().hashCode());
        result = prime * result + ((getOrderReviewStatus() == null) ? 0 : getOrderReviewStatus().hashCode());
        result = prime * result + ((getOrderPayMode() == null) ? 0 : getOrderPayMode().hashCode());
        result = prime * result + ((getOrderPlatformType() == null) ? 0 : getOrderPlatformType().hashCode());
        result = prime * result + ((getOrderDeliveryNumber() == null) ? 0 : getOrderDeliveryNumber().hashCode());
        result = prime * result + ((getOrderPayDate() == null) ? 0 : getOrderPayDate().hashCode());
        result = prime * result + ((getOrderShippingDate() == null) ? 0 : getOrderShippingDate().hashCode());
        result = prime * result + ((getOrderCheckStats() == null) ? 0 : getOrderCheckStats().hashCode());
        result = prime * result + ((getOrderCheckDate() == null) ? 0 : getOrderCheckDate().hashCode());
        result = prime * result + ((getOrderType() == null) ? 0 : getOrderType().hashCode());
        result = prime * result + ((getOrderMark() == null) ? 0 : getOrderMark().hashCode());
        result = prime * result + ((getRemark() == null) ? 0 : getRemark().hashCode());
        result = prime * result + ((getOrderPayWay() == null) ? 0 : getOrderPayWay().hashCode());
        result = prime * result + ((getPostToErpSuccess() == null) ? 0 : getPostToErpSuccess().hashCode());
        result = prime * result + ((getPostToErpStamp() == null) ? 0 : getPostToErpStamp().hashCode());
        result = prime * result + ((getDeliveryCompany() == null) ? 0 : getDeliveryCompany().hashCode());
        result = prime * result + ((getOnlinePayTotal() == null) ? 0 : getOnlinePayTotal().hashCode());
        result = prime * result + ((getBalancePayTotal() == null) ? 0 : getBalancePayTotal().hashCode());
        result = prime * result + ((getOrderCompleteDate() == null) ? 0 : getOrderCompleteDate().hashCode());
        result = prime * result + ((getExchageMoneyPointPay() == null) ? 0 : getExchageMoneyPointPay().hashCode());
        result = prime * result + ((getPointPay() == null) ? 0 : getPointPay().hashCode());
        result = prime * result + ((getIsPreSale() == null) ? 0 : getIsPreSale().hashCode());
        result = prime * result + ((getArrivalFlag() == null) ? 0 : getArrivalFlag().hashCode());
        result = prime * result + ((getDeliveryOrderId() == null) ? 0 : getDeliveryOrderId().hashCode());
        result = prime * result + ((getDeliveryDAddressCode() == null) ? 0 : getDeliveryDAddressCode().hashCode());
        result = prime * result + ((getRebateBalancePayTotal() == null) ? 0 : getRebateBalancePayTotal().hashCode());
        result = prime * result + ((getOfflinePayTotal() == null) ? 0 : getOfflinePayTotal().hashCode());
        result = prime * result + ((getScheduleOrderId() == null) ? 0 : getScheduleOrderId().hashCode());
        result = prime * result + ((getTotalWeight() == null) ? 0 : getTotalWeight().hashCode());
        result = prime * result + ((getAnonymous() == null) ? 0 : getAnonymous().hashCode());
        result = prime * result + ((getCrowdFundingItemId() == null) ? 0 : getCrowdFundingItemId().hashCode());
        result = prime * result + ((getDeleteStatus() == null) ? 0 : getDeleteStatus().hashCode());
        result = prime * result + ((getDeleteDate() == null) ? 0 : getDeleteDate().hashCode());
        result = prime * result + ((getRecommendCustomerId() == null) ? 0 : getRecommendCustomerId().hashCode());
        result = prime * result + ((getCoinId() == null) ? 0 : getCoinId().hashCode());
        result = prime * result + ((getCouponId() == null) ? 0 : getCouponId().hashCode());
        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
        result = prime * result + ((getOrderGift() == null) ? 0 : getOrderGift().hashCode());
        result = prime * result + ((getOrderTotalPay() == null) ? 0 : getOrderTotalPay().hashCode());
        result = prime * result + ((getUserDelete() == null) ? 0 : getUserDelete().hashCode());
        result = prime * result + ((getIsCanApplyService() == null) ? 0 : getIsCanApplyService().hashCode());
        result = prime * result + ((getInvoiceStatus() == null) ? 0 : getInvoiceStatus().hashCode());
        result = prime * result + ((getTransactionNo() == null) ? 0 : getTransactionNo().hashCode());
        result = prime * result + ((getSplitTransactionNo() == null) ? 0 : getSplitTransactionNo().hashCode());
        result = prime * result + ((getEfastSendStatus() == null) ? 0 : getEfastSendStatus().hashCode());
        result = prime * result + ((getOrderPayTime() == null) ? 0 : getOrderPayTime().hashCode());
        result = prime * result + ((getCompleteTime() == null) ? 0 : getCompleteTime().hashCode());
        result = prime * result + ((getConfireStatus() == null) ? 0 : getConfireStatus().hashCode());
        result = prime * result + ((getIsGroupPurchasing() == null) ? 0 : getIsGroupPurchasing().hashCode());
        result = prime * result + ((getWxMiniProgramLastUpdateTime() == null) ? 0 : getWxMiniProgramLastUpdateTime().hashCode());
        result = prime * result + ((getSplitOrderFlag() == null) ? 0 : getSplitOrderFlag().hashCode());
        result = prime * result + ((getIsEarnestAcitvity() == null) ? 0 : getIsEarnestAcitvity().hashCode());
        result = prime * result + ((getCustomerRemark() == null) ? 0 : getCustomerRemark().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", dateCreated=").append(dateCreated);
        sb.append(", dateUpdated=").append(dateUpdated);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", emailAddress=").append(emailAddress);
        sb.append(", name=").append(name);
        sb.append(", orderNumber=").append(orderNumber);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", orderSubtotal=").append(orderSubtotal);
        sb.append(", submitDate=").append(submitDate);
        sb.append(", orderTotal=").append(orderTotal);
        sb.append(", totalShipping=").append(totalShipping);
        sb.append(", totalTax=").append(totalTax);
        sb.append(", currencyCode=").append(currencyCode);
        sb.append(", customerId=").append(customerId);
        sb.append(", localeCode=").append(localeCode);
        sb.append(", orderShippingStatus=").append(orderShippingStatus);
        sb.append(", orderPayStatus=").append(orderPayStatus);
        sb.append(", orderReviewStatus=").append(orderReviewStatus);
        sb.append(", orderPayMode=").append(orderPayMode);
        sb.append(", orderPlatformType=").append(orderPlatformType);
        sb.append(", orderDeliveryNumber=").append(orderDeliveryNumber);
        sb.append(", orderPayDate=").append(orderPayDate);
        sb.append(", orderShippingDate=").append(orderShippingDate);
        sb.append(", orderCheckStats=").append(orderCheckStats);
        sb.append(", orderCheckDate=").append(orderCheckDate);
        sb.append(", orderType=").append(orderType);
        sb.append(", orderMark=").append(orderMark);
        sb.append(", remark=").append(remark);
        sb.append(", orderPayWay=").append(orderPayWay);
        sb.append(", postToErpSuccess=").append(postToErpSuccess);
        sb.append(", postToErpStamp=").append(postToErpStamp);
        sb.append(", deliveryCompany=").append(deliveryCompany);
        sb.append(", onlinePayTotal=").append(onlinePayTotal);
        sb.append(", balancePayTotal=").append(balancePayTotal);
        sb.append(", orderCompleteDate=").append(orderCompleteDate);
        sb.append(", exchageMoneyPointPay=").append(exchageMoneyPointPay);
        sb.append(", pointPay=").append(pointPay);
        sb.append(", isPreSale=").append(isPreSale);
        sb.append(", arrivalFlag=").append(arrivalFlag);
        sb.append(", deliveryOrderId=").append(deliveryOrderId);
        sb.append(", deliveryDAddressCode=").append(deliveryDAddressCode);
        sb.append(", rebateBalancePayTotal=").append(rebateBalancePayTotal);
        sb.append(", offlinePayTotal=").append(offlinePayTotal);
        sb.append(", scheduleOrderId=").append(scheduleOrderId);
        sb.append(", totalWeight=").append(totalWeight);
        sb.append(", anonymous=").append(anonymous);
        sb.append(", crowdFundingItemId=").append(crowdFundingItemId);
        sb.append(", deleteStatus=").append(deleteStatus);
        sb.append(", deleteDate=").append(deleteDate);
        sb.append(", recommendCustomerId=").append(recommendCustomerId);
        sb.append(", coinId=").append(coinId);
        sb.append(", couponId=").append(couponId);
        sb.append(", payType=").append(payType);
        sb.append(", orderGift=").append(orderGift);
        sb.append(", orderTotalPay=").append(orderTotalPay);
        sb.append(", userDelete=").append(userDelete);
        sb.append(", isCanApplyService=").append(isCanApplyService);
        sb.append(", invoiceStatus=").append(invoiceStatus);
        sb.append(", transactionNo=").append(transactionNo);
        sb.append(", splitTransactionNo=").append(splitTransactionNo);
        sb.append(", efastSendStatus=").append(efastSendStatus);
        sb.append(", orderPayTime=").append(orderPayTime);
        sb.append(", completeTime=").append(completeTime);
        sb.append(", confireStatus=").append(confireStatus);
        sb.append(", isGroupPurchasing=").append(isGroupPurchasing);
        sb.append(", wxMiniProgramLastUpdateTime=").append(wxMiniProgramLastUpdateTime);
        sb.append(", splitOrderFlag=").append(splitOrderFlag);
        sb.append(", isEarnestAcitvity=").append(isEarnestAcitvity);
        sb.append(", customerRemark=").append(customerRemark);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}