package com.gialen.tools.dao.entity.customer;

import java.io.Serializable;
import java.util.Date;

public class UserLevelChangeLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.old_level_type
     *
     * @mbg.generated
     */
    private Byte oldLevelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.new_level_type
     *
     * @mbg.generated
     */
    private Byte newLevelType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.channel
     *
     * @mbg.generated
     */
    private Byte channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.valid_start_time
     *
     * @mbg.generated
     */
    private Date validStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.valid_end_time
     *
     * @mbg.generated
     */
    private Date validEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_level_change_log.process_time
     *
     * @mbg.generated
     */
    private Date processTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.id
     *
     * @return the value of user_level_change_log.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.id
     *
     * @param id the value for user_level_change_log.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.user_id
     *
     * @return the value of user_level_change_log.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.user_id
     *
     * @param userId the value for user_level_change_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.old_level_type
     *
     * @return the value of user_level_change_log.old_level_type
     *
     * @mbg.generated
     */
    public Byte getOldLevelType() {
        return oldLevelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.old_level_type
     *
     * @param oldLevelType the value for user_level_change_log.old_level_type
     *
     * @mbg.generated
     */
    public void setOldLevelType(Byte oldLevelType) {
        this.oldLevelType = oldLevelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.new_level_type
     *
     * @return the value of user_level_change_log.new_level_type
     *
     * @mbg.generated
     */
    public Byte getNewLevelType() {
        return newLevelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.new_level_type
     *
     * @param newLevelType the value for user_level_change_log.new_level_type
     *
     * @mbg.generated
     */
    public void setNewLevelType(Byte newLevelType) {
        this.newLevelType = newLevelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.channel
     *
     * @return the value of user_level_change_log.channel
     *
     * @mbg.generated
     */
    public Byte getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.channel
     *
     * @param channel the value for user_level_change_log.channel
     *
     * @mbg.generated
     */
    public void setChannel(Byte channel) {
        this.channel = channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.valid_start_time
     *
     * @return the value of user_level_change_log.valid_start_time
     *
     * @mbg.generated
     */
    public Date getValidStartTime() {
        return validStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.valid_start_time
     *
     * @param validStartTime the value for user_level_change_log.valid_start_time
     *
     * @mbg.generated
     */
    public void setValidStartTime(Date validStartTime) {
        this.validStartTime = validStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.valid_end_time
     *
     * @return the value of user_level_change_log.valid_end_time
     *
     * @mbg.generated
     */
    public Date getValidEndTime() {
        return validEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.valid_end_time
     *
     * @param validEndTime the value for user_level_change_log.valid_end_time
     *
     * @mbg.generated
     */
    public void setValidEndTime(Date validEndTime) {
        this.validEndTime = validEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.create_time
     *
     * @return the value of user_level_change_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.create_time
     *
     * @param createTime the value for user_level_change_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.update_time
     *
     * @return the value of user_level_change_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.update_time
     *
     * @param updateTime the value for user_level_change_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_level_change_log.process_time
     *
     * @return the value of user_level_change_log.process_time
     *
     * @mbg.generated
     */
    public Date getProcessTime() {
        return processTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_level_change_log.process_time
     *
     * @param processTime the value for user_level_change_log.process_time
     *
     * @mbg.generated
     */
    public void setProcessTime(Date processTime) {
        this.processTime = processTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        UserLevelChangeLog other = (UserLevelChangeLog) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOldLevelType() == null ? other.getOldLevelType() == null : this.getOldLevelType().equals(other.getOldLevelType()))
            && (this.getNewLevelType() == null ? other.getNewLevelType() == null : this.getNewLevelType().equals(other.getNewLevelType()))
            && (this.getChannel() == null ? other.getChannel() == null : this.getChannel().equals(other.getChannel()))
            && (this.getValidStartTime() == null ? other.getValidStartTime() == null : this.getValidStartTime().equals(other.getValidStartTime()))
            && (this.getValidEndTime() == null ? other.getValidEndTime() == null : this.getValidEndTime().equals(other.getValidEndTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getProcessTime() == null ? other.getProcessTime() == null : this.getProcessTime().equals(other.getProcessTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOldLevelType() == null) ? 0 : getOldLevelType().hashCode());
        result = prime * result + ((getNewLevelType() == null) ? 0 : getNewLevelType().hashCode());
        result = prime * result + ((getChannel() == null) ? 0 : getChannel().hashCode());
        result = prime * result + ((getValidStartTime() == null) ? 0 : getValidStartTime().hashCode());
        result = prime * result + ((getValidEndTime() == null) ? 0 : getValidEndTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getProcessTime() == null) ? 0 : getProcessTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", oldLevelType=").append(oldLevelType);
        sb.append(", newLevelType=").append(newLevelType);
        sb.append(", channel=").append(channel);
        sb.append(", validStartTime=").append(validStartTime);
        sb.append(", validEndTime=").append(validEndTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", processTime=").append(processTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}