package com.gialen.tools.dao.repository.gialen;

import com.gialen.tools.dao.entity.gialen.BlcCustomer;
import com.gialen.tools.dao.entity.gialen.BlcCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@org.springframework.stereotype.Repository
public interface BlcCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    long countByExample(BlcCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int deleteByExample(BlcCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int insert(BlcCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int insertSelective(BlcCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    List<BlcCustomer> selectByExampleWithBLOBs(BlcCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    List<BlcCustomer> selectByExample(BlcCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    BlcCustomer selectByPrimaryKey(Long customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlcCustomer record, @Param("example") BlcCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") BlcCustomer record, @Param("example") BlcCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlcCustomer record, @Param("example") BlcCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlcCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(BlcCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blc_customer
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlcCustomer record);
}