package com.gialen.tools.dao.repository.gialen;

import com.gialen.tools.dao.entity.gialen.RomaStore;
import com.gialen.tools.dao.entity.gialen.RomaStoreExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@org.springframework.stereotype.Repository
public interface RomaStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    long countByExample(RomaStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int deleteByExample(RomaStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int insert(RomaStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int insertSelective(RomaStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    List<RomaStore> selectByExample(RomaStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    RomaStore selectByPrimaryKey(Integer storeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RomaStore record, @Param("example") RomaStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RomaStore record, @Param("example") RomaStoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RomaStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roma_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RomaStore record);
}