package com.gialen.tools.dao.entity.order;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_sn
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_type
     *
     * @mbg.generated
     */
    private Short orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status
     *
     * @mbg.generated
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_money
     *
     * @mbg.generated
     */
    private BigDecimal payMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_money_snapshot
     *
     * @mbg.generated
     */
    private BigDecimal payMoneySnapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.freight
     *
     * @mbg.generated
     */
    private BigDecimal freight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.fav_money
     *
     * @mbg.generated
     */
    private BigDecimal favMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.wallet_money_snapshot
     *
     * @mbg.generated
     */
    private BigDecimal walletMoneySnapshot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.wallet_money
     *
     * @mbg.generated
     */
    private BigDecimal walletMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.money
     *
     * @mbg.generated
     */
    private BigDecimal money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_type
     *
     * @mbg.generated
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_sn
     *
     * @mbg.generated
     */
    private String paySn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_status
     *
     * @mbg.generated
     */
    private Short payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_time
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.flow_flag
     *
     * @mbg.generated
     */
    private Short flowFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.send_time
     *
     * @mbg.generated
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.received_time
     *
     * @mbg.generated
     */
    private Date receivedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.platform
     *
     * @mbg.generated
     */
    private Short platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_parent
     *
     * @mbg.generated
     */
    private Boolean isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.parent_order_sn
     *
     * @mbg.generated
     */
    private String parentOrderSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.data_version
     *
     * @mbg.generated
     */
    private Integer dataVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_hidden
     *
     * @mbg.generated
     */
    private Boolean isHidden;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.is_new_order
     *
     * @mbg.generated
     */
    private Boolean isNewOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_sn
     *
     * @return the value of orders.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_sn
     *
     * @param orderSn the value for orders.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_type
     *
     * @return the value of orders.order_type
     *
     * @mbg.generated
     */
    public Short getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_type
     *
     * @param orderType the value for orders.order_type
     *
     * @mbg.generated
     */
    public void setOrderType(Short orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbg.generated
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param orderStatus the value for orders.order_status
     *
     * @mbg.generated
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_money
     *
     * @return the value of orders.pay_money
     *
     * @mbg.generated
     */
    public BigDecimal getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_money
     *
     * @param payMoney the value for orders.pay_money
     *
     * @mbg.generated
     */
    public void setPayMoney(BigDecimal payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_money_snapshot
     *
     * @return the value of orders.pay_money_snapshot
     *
     * @mbg.generated
     */
    public BigDecimal getPayMoneySnapshot() {
        return payMoneySnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_money_snapshot
     *
     * @param payMoneySnapshot the value for orders.pay_money_snapshot
     *
     * @mbg.generated
     */
    public void setPayMoneySnapshot(BigDecimal payMoneySnapshot) {
        this.payMoneySnapshot = payMoneySnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.freight
     *
     * @return the value of orders.freight
     *
     * @mbg.generated
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.freight
     *
     * @param freight the value for orders.freight
     *
     * @mbg.generated
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.fav_money
     *
     * @return the value of orders.fav_money
     *
     * @mbg.generated
     */
    public BigDecimal getFavMoney() {
        return favMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.fav_money
     *
     * @param favMoney the value for orders.fav_money
     *
     * @mbg.generated
     */
    public void setFavMoney(BigDecimal favMoney) {
        this.favMoney = favMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.wallet_money_snapshot
     *
     * @return the value of orders.wallet_money_snapshot
     *
     * @mbg.generated
     */
    public BigDecimal getWalletMoneySnapshot() {
        return walletMoneySnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.wallet_money_snapshot
     *
     * @param walletMoneySnapshot the value for orders.wallet_money_snapshot
     *
     * @mbg.generated
     */
    public void setWalletMoneySnapshot(BigDecimal walletMoneySnapshot) {
        this.walletMoneySnapshot = walletMoneySnapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.wallet_money
     *
     * @return the value of orders.wallet_money
     *
     * @mbg.generated
     */
    public BigDecimal getWalletMoney() {
        return walletMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.wallet_money
     *
     * @param walletMoney the value for orders.wallet_money
     *
     * @mbg.generated
     */
    public void setWalletMoney(BigDecimal walletMoney) {
        this.walletMoney = walletMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.money
     *
     * @return the value of orders.money
     *
     * @mbg.generated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.money
     *
     * @param money the value for orders.money
     *
     * @mbg.generated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_type
     *
     * @return the value of orders.pay_type
     *
     * @mbg.generated
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_type
     *
     * @param payType the value for orders.pay_type
     *
     * @mbg.generated
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_sn
     *
     * @return the value of orders.pay_sn
     *
     * @mbg.generated
     */
    public String getPaySn() {
        return paySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_sn
     *
     * @param paySn the value for orders.pay_sn
     *
     * @mbg.generated
     */
    public void setPaySn(String paySn) {
        this.paySn = paySn == null ? null : paySn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_status
     *
     * @return the value of orders.pay_status
     *
     * @mbg.generated
     */
    public Short getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_status
     *
     * @param payStatus the value for orders.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Short payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_time
     *
     * @return the value of orders.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_time
     *
     * @param payTime the value for orders.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.flow_flag
     *
     * @return the value of orders.flow_flag
     *
     * @mbg.generated
     */
    public Short getFlowFlag() {
        return flowFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.flow_flag
     *
     * @param flowFlag the value for orders.flow_flag
     *
     * @mbg.generated
     */
    public void setFlowFlag(Short flowFlag) {
        this.flowFlag = flowFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.send_time
     *
     * @return the value of orders.send_time
     *
     * @mbg.generated
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.send_time
     *
     * @param sendTime the value for orders.send_time
     *
     * @mbg.generated
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.received_time
     *
     * @return the value of orders.received_time
     *
     * @mbg.generated
     */
    public Date getReceivedTime() {
        return receivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.received_time
     *
     * @param receivedTime the value for orders.received_time
     *
     * @mbg.generated
     */
    public void setReceivedTime(Date receivedTime) {
        this.receivedTime = receivedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.del_flag
     *
     * @return the value of orders.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.del_flag
     *
     * @param delFlag the value for orders.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.platform
     *
     * @return the value of orders.platform
     *
     * @mbg.generated
     */
    public Short getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.platform
     *
     * @param platform the value for orders.platform
     *
     * @mbg.generated
     */
    public void setPlatform(Short platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_parent
     *
     * @return the value of orders.is_parent
     *
     * @mbg.generated
     */
    public Boolean getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_parent
     *
     * @param isParent the value for orders.is_parent
     *
     * @mbg.generated
     */
    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.parent_order_sn
     *
     * @return the value of orders.parent_order_sn
     *
     * @mbg.generated
     */
    public String getParentOrderSn() {
        return parentOrderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.parent_order_sn
     *
     * @param parentOrderSn the value for orders.parent_order_sn
     *
     * @mbg.generated
     */
    public void setParentOrderSn(String parentOrderSn) {
        this.parentOrderSn = parentOrderSn == null ? null : parentOrderSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.data_version
     *
     * @return the value of orders.data_version
     *
     * @mbg.generated
     */
    public Integer getDataVersion() {
        return dataVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.data_version
     *
     * @param dataVersion the value for orders.data_version
     *
     * @mbg.generated
     */
    public void setDataVersion(Integer dataVersion) {
        this.dataVersion = dataVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_hidden
     *
     * @return the value of orders.is_hidden
     *
     * @mbg.generated
     */
    public Boolean getIsHidden() {
        return isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_hidden
     *
     * @param isHidden the value for orders.is_hidden
     *
     * @mbg.generated
     */
    public void setIsHidden(Boolean isHidden) {
        this.isHidden = isHidden;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.update_time
     *
     * @return the value of orders.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.update_time
     *
     * @param updateTime the value for orders.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.create_time
     *
     * @return the value of orders.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.create_time
     *
     * @param createTime the value for orders.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.is_new_order
     *
     * @return the value of orders.is_new_order
     *
     * @mbg.generated
     */
    public Boolean getIsNewOrder() {
        return isNewOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.is_new_order
     *
     * @param isNewOrder the value for orders.is_new_order
     *
     * @mbg.generated
     */
    public void setIsNewOrder(Boolean isNewOrder) {
        this.isNewOrder = isNewOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Orders other = (Orders) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderSn() == null ? other.getOrderSn() == null : this.getOrderSn().equals(other.getOrderSn()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getOrderType() == null ? other.getOrderType() == null : this.getOrderType().equals(other.getOrderType()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getPayMoney() == null ? other.getPayMoney() == null : this.getPayMoney().equals(other.getPayMoney()))
            && (this.getPayMoneySnapshot() == null ? other.getPayMoneySnapshot() == null : this.getPayMoneySnapshot().equals(other.getPayMoneySnapshot()))
            && (this.getFreight() == null ? other.getFreight() == null : this.getFreight().equals(other.getFreight()))
            && (this.getFavMoney() == null ? other.getFavMoney() == null : this.getFavMoney().equals(other.getFavMoney()))
            && (this.getWalletMoneySnapshot() == null ? other.getWalletMoneySnapshot() == null : this.getWalletMoneySnapshot().equals(other.getWalletMoneySnapshot()))
            && (this.getWalletMoney() == null ? other.getWalletMoney() == null : this.getWalletMoney().equals(other.getWalletMoney()))
            && (this.getMoney() == null ? other.getMoney() == null : this.getMoney().equals(other.getMoney()))
            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
            && (this.getPaySn() == null ? other.getPaySn() == null : this.getPaySn().equals(other.getPaySn()))
            && (this.getPayStatus() == null ? other.getPayStatus() == null : this.getPayStatus().equals(other.getPayStatus()))
            && (this.getPayTime() == null ? other.getPayTime() == null : this.getPayTime().equals(other.getPayTime()))
            && (this.getFlowFlag() == null ? other.getFlowFlag() == null : this.getFlowFlag().equals(other.getFlowFlag()))
            && (this.getSendTime() == null ? other.getSendTime() == null : this.getSendTime().equals(other.getSendTime()))
            && (this.getReceivedTime() == null ? other.getReceivedTime() == null : this.getReceivedTime().equals(other.getReceivedTime()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()))
            && (this.getPlatform() == null ? other.getPlatform() == null : this.getPlatform().equals(other.getPlatform()))
            && (this.getIsParent() == null ? other.getIsParent() == null : this.getIsParent().equals(other.getIsParent()))
            && (this.getParentOrderSn() == null ? other.getParentOrderSn() == null : this.getParentOrderSn().equals(other.getParentOrderSn()))
            && (this.getDataVersion() == null ? other.getDataVersion() == null : this.getDataVersion().equals(other.getDataVersion()))
            && (this.getIsHidden() == null ? other.getIsHidden() == null : this.getIsHidden().equals(other.getIsHidden()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getIsNewOrder() == null ? other.getIsNewOrder() == null : this.getIsNewOrder().equals(other.getIsNewOrder()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderSn() == null) ? 0 : getOrderSn().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getOrderType() == null) ? 0 : getOrderType().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getPayMoney() == null) ? 0 : getPayMoney().hashCode());
        result = prime * result + ((getPayMoneySnapshot() == null) ? 0 : getPayMoneySnapshot().hashCode());
        result = prime * result + ((getFreight() == null) ? 0 : getFreight().hashCode());
        result = prime * result + ((getFavMoney() == null) ? 0 : getFavMoney().hashCode());
        result = prime * result + ((getWalletMoneySnapshot() == null) ? 0 : getWalletMoneySnapshot().hashCode());
        result = prime * result + ((getWalletMoney() == null) ? 0 : getWalletMoney().hashCode());
        result = prime * result + ((getMoney() == null) ? 0 : getMoney().hashCode());
        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
        result = prime * result + ((getPaySn() == null) ? 0 : getPaySn().hashCode());
        result = prime * result + ((getPayStatus() == null) ? 0 : getPayStatus().hashCode());
        result = prime * result + ((getPayTime() == null) ? 0 : getPayTime().hashCode());
        result = prime * result + ((getFlowFlag() == null) ? 0 : getFlowFlag().hashCode());
        result = prime * result + ((getSendTime() == null) ? 0 : getSendTime().hashCode());
        result = prime * result + ((getReceivedTime() == null) ? 0 : getReceivedTime().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        result = prime * result + ((getPlatform() == null) ? 0 : getPlatform().hashCode());
        result = prime * result + ((getIsParent() == null) ? 0 : getIsParent().hashCode());
        result = prime * result + ((getParentOrderSn() == null) ? 0 : getParentOrderSn().hashCode());
        result = prime * result + ((getDataVersion() == null) ? 0 : getDataVersion().hashCode());
        result = prime * result + ((getIsHidden() == null) ? 0 : getIsHidden().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIsNewOrder() == null) ? 0 : getIsNewOrder().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", userId=").append(userId);
        sb.append(", orderType=").append(orderType);
        sb.append(", orderStatus=").append(orderStatus);
        sb.append(", payMoney=").append(payMoney);
        sb.append(", payMoneySnapshot=").append(payMoneySnapshot);
        sb.append(", freight=").append(freight);
        sb.append(", favMoney=").append(favMoney);
        sb.append(", walletMoneySnapshot=").append(walletMoneySnapshot);
        sb.append(", walletMoney=").append(walletMoney);
        sb.append(", money=").append(money);
        sb.append(", payType=").append(payType);
        sb.append(", paySn=").append(paySn);
        sb.append(", payStatus=").append(payStatus);
        sb.append(", payTime=").append(payTime);
        sb.append(", flowFlag=").append(flowFlag);
        sb.append(", sendTime=").append(sendTime);
        sb.append(", receivedTime=").append(receivedTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", platform=").append(platform);
        sb.append(", isParent=").append(isParent);
        sb.append(", parentOrderSn=").append(parentOrderSn);
        sb.append(", dataVersion=").append(dataVersion);
        sb.append(", isHidden=").append(isHidden);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", createTime=").append(createTime);
        sb.append(", isNewOrder=").append(isNewOrder);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}