package com.gialen.tools.dao.repository.customer;

import com.gialen.tools.dao.entity.customer.UserLevelChangeLog;
import com.gialen.tools.dao.entity.customer.UserLevelChangeLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

@org.springframework.stereotype.Repository
public interface UserLevelChangeLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    long countByExample(UserLevelChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int deleteByExample(UserLevelChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int insert(UserLevelChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int insertSelective(UserLevelChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    List<UserLevelChangeLog> selectByExample(UserLevelChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    UserLevelChangeLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserLevelChangeLog record, @Param("example") UserLevelChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserLevelChangeLog record, @Param("example") UserLevelChangeLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserLevelChangeLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_level_change_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserLevelChangeLog record);
}